### ISSUE TITLE
Allow DEAP pypy version to fail

### ISSUE THREAD

**Issue by fmder** [DEAP/deap#98]
Since PyPy is far from stable, we could allow the PyPy CI to fail with 
```yaml
matrix:
  allow_failures:
    - python: "pypy"
```
As suggested by @hashhsah in #97
